name: Testing1
on: 
  push
# workflow_dispatch:
#    inputs:
#      mergeToReleases:
#        default: 'false'

jobs: 
  dev-job:
    name: Build ESM Test
    runs-on: [self-hosted, Linux, X64, dev]
#    runs-on: ubuntu-18.04
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2

      - name: Clean ESM System Environment
        run: |
          echo TBD
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi -f $(docker images -q)
          sudo rm -rf /opt/Logs
          sudo rm -rf /opt/containerd

      - name: Build ESM Docker
        run: | 
          sudo mv SecBuzzerESM /opt/.
          sudo bash /opt/SecBuzzerESM/Install.sh
      - name: checkout Logs folder
        run: |
          sudo ls -al /opt/Logs/Suricata/
          sudo ./opt/SecBuzzerESM/compose.sh up
      - name: check all container status
        run: docker ps -a

