name: Testing1
on: 
  push
# workflow_dispatch:
#    inputs:
#      mergeToReleases:
#        default: 'false'

jobs: 
  dev-job:
    name: Build ESM Test
    runs-on: [self-hosted, Linux, X64, dev]
#    runs-on: ubuntu-18.04
    steps:
#      - uses: AutoModality/action-clean@v1
#      - uses: actions/checkout@v2

#      - name: Clean ESM System Environment
#        run: |
#          echo TBD
#          docker rmi -f $(docker images -q)

      - name: Build ESM Docker
        run: | 
          sudo source SecBuzzerESM/Install.sh
      - name: checkout Logs folder
        run: |
          sudo ls -al /opt/Logs/Suricata/

